# -*- coding: utf-8 -*-
"""Workshop Class 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TqWudJUonP9hYFj_iH0uQIytzK61AfGg
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import plotly.express as pr
import plotly.graph_objects as go

#read the data set
df = pd.read_csv('/content/drive/MyDrive/project_dataset.csv')

df

df1 = df.copy()

df1.head

df.head(60)

df.shape

df1.columns

df1.dtypes

df1.info()

df1.describe()

df.duplicated()

df1.isna()

df1.isna().sum()

df1.isna().sum()/df1.shape[0]

df1.dropna(axis = 1, inplace = True)

df1

df1.dtypes

df1.shape

data = df1.sample(n = 500, random_state = 42)

data

data.shape
data.columns
data.head()
data.tail

data.count()

data = data.drop(['Unnamed: 0'], axis = 1)

data.shape

data

fig = go.Figure(data =go.Scatter(x=df['Distance'], y =df['DepTime'],mode='markers', marker=dict(color='red')))

fig.update_layout(title='Scatter PLot for Distance vs Departure time', xaxis_title = 'Distance', yaxis_title='Deparute time')
fig.show()

line_data = df.groupby('Month')['ArrDelay'].mean().reset_index()

line_data

fig = go.Figure(data =go.Scatter(x=line_data['Month'], y =line_data['ArrDelay'],mode='lines', marker=dict(color='green')))
fig.update_layout(title='Monthly average delay plot for an year', xaxis_title = 'Months', yaxis_title='Delay of Flights in minutes')
fig.show()

bar_data = df.groupby('DestState')['Flights'].sum().reset_index()
bar_data

fig = pr.bar(bar_data, x = 'DestState', y = 'Flights', title = 'Total number of flights from each destination states')
fig.show()

bub_data = df.groupby('Reporting_Airline')['Flights'].sum().reset_index()

bub_data

fig_bub= pr.scatter(bub_data, x = 'Reporting_Airline', y ='Flights', title = 'Total number of flights per reporting airlines', size ="Flights", hover_name='Reporting_Airline', size_max=60)
fig_bub.show()

